export const surpriseMePrompts = [
  "A vibrant truck art design featuring iconic Pakistani landmarks",
  "A surrealist oil painting of the ancient Indus Valley civilization in a futuristic setting",
  "Traditional Pakistani wedding scene with a modern twist, digital art",
  "An oil painting of a cricket match in Gwadar Port, with futuristic ships in the background",
  "Lahore's Badshahi Mosque reimagined as a space station, digital art",
  "A macro photograph of a elaborate henna design telling the story of Pakistan's independence",
  "3D render of a cute snow leopard wearing traditional Pakistani clothing in the Karakoram mountains",
  "An astronaut enjoying a cup of Kashmiri chai on K2, vaporwave style",
  "An oil painting portrait of Quaid-e-Azam in cyberpunk attire with Karachi skyline in the background",
  "A stained glass window depicting the national flowers of Pakistan's provinces",
  "A pencil and watercolor drawing of Islamabad in 2100 with eco-friendly architecture and flying electric rickshaws",
  "A sunlit courtyard of Lahore Fort with holographic Mughal era characters, digital art",
  "A fortune-telling Markhor predicting Pakistan's future through a crystal ball, digital art",
  '"The Girl with a Jasmine Flower" in the style of Johannes Vermeer, set in Sindh',
  "An oil pastel drawing of an annoyed camel in a spaceship over the Thar Desert",
  "A painting of the Indus River Delta in the style of Starry Night",
  "A bowl of nihari that looks like a friendly monster, knitted out of wool",
  "A plush toy robot wearing a traditional Balochi hat against a backdrop of Quetta",
  "A synthwave style sunset over the Arabian Sea with Clifton Beach in the foreground, digital art",
  "Two futuristic minarets of Faisal Mosque with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above Attabad Lake",
  "A comic book cover of a superhero inspired by Pakistani folklore",
  "A centered explosion of colorful powder representing Holi celebrations in Pakistan",
  "A photo of a Pakistani Mastiff with its tongue out hugging a black Bombay cat",
  "A photo of a white Markhor standing majestically in Deosai Plains",
  "A photo of the Minar-e-Pakistan wearing headphones and DJing",
  "A Mughal emperor riding a horse on Mars, lomography",
  "A modern, sleek Pakistani-made electric car drives along M2 Motorway with Islamabad in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with hazel eyes wearing a traditional Sindhi cap",
  "A man standing in front of a portal to ancient Mohenjo-daro",
  "Allama Iqbal in a science fiction movie poster",
  "A snow leopard working at a chai dhaba in Hunza Valley, lomography",
  "A person walking through the bustling streets of Empress Market in Karachi at night, lit by many bright shop signs, 50mm lens",
  "A plate of biryani that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg mehfil, with neon-lit instruments",
  "The long-lost Pakistani 1990 anime adaptation of Allama Iqbal's poetry",
  "A seekh kebab in the shape of a Rubik's cube, professional food photography",
  "A Synthwave Chukkar, inspired by Indus Valley seals",
  "An astronaut encountering an ancient Indus Valley deity on a distant planet, photography",
  "A Dinosaur exploring the ruins of Mohenjo-daro, photography",
  "A person falling in love with AI-powered Urdu poetry, digital art",
  "A photograph of a cyborg exploring Peshawar's Qissa Khwani Bazaar at night, lomography",
  "Ranjit Singh walking down the streets of modern-day Lahore, black and white photography",
  "Synthwave PIA airplane",
  "A person wanders through the rainy streets of Murree, with bright hotel signs, 50mm",
  "The International Space Station flying above the Karakoram Highway, digital art",
];
